- M80-M81/README.md
- M80-M81/parser_m80_m81.c
- added M80 (PSU ON) M81 (PSU OFF) module extension
> Added M80-M81 module

- M62-M65/README.md
- M62-M65/parser_m62_m65.c
- implemented LinuxCNC M62-M65
> implemented LinuxCNC M62-M65

- BLTouch/CHANGELOG.md
- BLTouch/bltouch.c
- Examples/extended_grbl_cmd.c
- Examples/extended_mcode.c
- Examples/extended_task.c
- I2C LCD/CHANGELOG.md
- I2C LCD/i2c_lcd.c
- M17-M18/CHANGELOG.md
- M17-M18/parser_m17_m18.c
- M42/CHANGELOG.md
- M42/parser_m42.c
- M62-M65/CHANGELOG.md
- M62-M65/parser_m62_m65.c
- M67-M68/CHANGELOG.md
- M67-M68/parser_m67_m68.c
- M80-M81/CHANGELOG.md
- M80-M81/parser_m80_m81.c
- README.md
- updated modules to match unified callback definition for version 1.5 of µCNC
> update v1.5 (unified callback)

- I2C_LCD/CHANGELOG.md
- I2C_LCD/README.md
- I2C_LCD/i2c_lcd.c
- SD_card/CHANGELOG.md
LCD I2C rewrite to match new I2C core functions
> LCD I2C rewrite

- SD_card/CHANGELOG.md
- SD_card/diskio.c
- SD_card/mmcsd.h
- SD_card/sd_card.c
- fixed sd card detection and writing
- added support for settings storing in sd card
> SD card fixes and new features

- Smoothie_clustering/CHANGELOG.md
- Smoothie_clustering/smoothie_clustering.c
- added S clustering options to $I command
- configurable buffer size
> Smoothie clustering print options

- Examples/extended_setting.c
- SD_card/CHANGELOG.md
- SD_card/sd_card.c
- Update sd card settings to allow multiple settings event listeners
> Update sd card settings

- G5/CHANGELOG.md
- G5/README.md
- G5/parser_g5.c
- G5 and G5.1 extension module
> G5 extension

- G33/CHANGELOG.md
- G33/README.md
- G33/parser_g33.c
- support for G33 (lathe mode spindle synched motion for threading)
> added module for G33 GCode support

- G7-G8/CHANGELOG.md
- G7-G8/README.md
- G7-G8/parser_g7_g8.c
Add LinuxCNC G7-G8 gcodes to control lathe radius mode
> G7-G8 parser extension module

- graphic_display/graphic_display.c
- added modal popup handler for graphic display
- supports multiline messages
> added modal popup handler for graphic display

- SD_card/CHANGELOG.md
- SD_card/ffconf.h
- SD_card/sd_card.c
- SD_card/sd_messages.h
- initial inegration of system menu module into SD card module
- allow to navigate through the card inside the graphic display
> SD system menu

- graphic_display/CHANGELOG.md
- graphic_display/graphic_display.c
- slight change to idle screen elements position
- header render prints RAM string
- modified startup code
> Graphic display modify idle screen

- M66/CHANGELOG.md
- M66/README.md
- M66/parser_m66.c
implementation of [M66](https://linuxcnc.org/docs/html/gcode/m-code.html#mcode:m66)
> M66 module

- graphic_display/CHANGELOG.md
- graphic_display/graphic_display.c
- added long press (5s) on button to do soft reset
- added alarm screen popup
> added soft reset via btn and alarm popup

- G28_1-G30_1/CHANGELOG.md
- G28_1-G30_1/README.md
- G28_1-G30_1/parser_g28_1_g30_1.c
- implemented G28.1-G30.1 module
> G28.1-G30.1 module

- tmc_driver/CHANGELOG.md
- tmc_driver/README.md
- tmc_driver/tmc.c
- tmc_driver/tmc.h
- tmc_driver/tmc_bitfields.h
- tmc_driver/tmc_driver.c
- tmc_driver/tmc_driver.h
- modified set functions to match a callback
- m commands only update the respective function now
- improved shadow registers
- added missing the bitfields
> final integration of tmc driver as module

- I2C_LCD/CHANGELOG.md
- I2C_LCD/i2c_lcd.c
- graphic_display/CHANGELOG.md
- graphic_display/graphic_display.c
- modifications to i2s to incorporate timeout in sending calls
> updated modules for v010808

- tmc_driver/CHANGELOG.md
- tmc_driver/tmc_driver.c
- tmc_driver/tmc_driver.h
- configurable baudrate for each tmc uart driver
- fixed UART timeout calculations
> configurable baudrate for each tmc uart driver

- tmc_driver/CHANGELOG.md
- tmc_driver/tmc_driver.c
- tmc_driver/tmc_driver.h
- added TMC driver support for hw UART2 and SPI
> TMC driver support for hw UART2 and SPI

- grblhal_keypad/CHANGELOG.md
- grblhal_keypad/grblhal_keypad.c
- added support for multiline macros
> Keypad macro support

- grblhal_keypad/CHANGELOG.md
- grblhal_keypad/grblhal_keypad.c
- fixed strobe key handling and releasing
- fixed macro code CR termination
- handling of realtime codes in ISR
> Fix keypad strobe pulse

- graphic_display/graphic_display.c
- graphic_display/graphic_display.h
- graphic_display/graphic_display_u8g2.c
Update module display up to version 11000
> v11000 display module update

- sd_card_v2/diskio.c
- sd_card_v2/diskio.h
- sd_card_v2/fat_fs/ffconf.h
- sd_card_v2/sd_card_v2.c
- sd_card_v2/sd_messages.h
Updated SD Card v2 module to v11000
> Updated SD Card v2 module to v11000

- touch_screen/CHANGELOG.md
- touch_screen/touch_screen.c
- touch_screen/touch_screen.h
- fixed touch screen rotation
- simplified configuration on init function
> fixed touch screen rotation

- lvgl/lvgl_support.c
- lvgl/lvgl_support.h
- lvgl/style/win9x/bitmaps/dropdown_arrow.h
- lvgl/style/win9x/colors.h
- lvgl/style/win9x/elements.c
- lvgl/style/win9x/elements.h
- lvgl/style/win9x/elements/buttons.c
- lvgl/style/win9x/elements/coordinate_table.c
- lvgl/style/win9x/elements/number_input.c
- lvgl/style/win9x/main.c
- lvgl/style/win9x/screens/idle.c
- lvgl/style/win9x/screens/jog.c
- lvgl/style/win9x/screens/list_menu.c
- lvgl/style/win9x/screens/movement.c
- lvgl/style/win9x/screens/startup.c
- lvgl/style/win9x/styles.h
A couple of things I found while using the GUI.
- Changed event type for buttons to LV_EVENT_CLICKED, this prevents things from getting clicked after a screen switch.
- Improved movement screen
- Added custom jogging screen
- Split `elements.c` for better readability
- Added `lvgl_serial_putc` to remove the use of sprintf
> LVGL module and Win9x theme improvements

- tft_display/CHANGELOG.md
- tft_display/README.md
- tft_display/tft_display.c
- added support for touch screen
> added support for touch screen on tft display

- mks_display/lv_conf.h
- mks_display/mks_display.c
- touch_screen/touch_screen.c
- redefined default IO pins
- added touch debug optional flag
-  added bit swap optional test flag
- fixed screen rotation
- added tft and touch optional flags
- added bkl and rst pin inversion options
> fixes on mks display and touch modules

- i2c_eeprom/i2c_eeprom.c
- new module to allow usage of external EEPROM memories to store settings
> I2C External EEPROM

- sd_card_v2/CHANGELOG.md
- sd_card_v2/diskio.c
- sd_card_v2/sd_card_v2.c
- Fix SD Card file open/create if file does not exist
- Removed SPI operation time print out message
> Fix SD Card file open/create if file does not exist

- m62_m65/CHANGELOG.md
- m62_m65/parser_m62_m65.c
- fix execution parsing bug of the M codes
> fix execution parsing bug

- g28_1_g30_1/CHANGELOG.md
- g28_1_g30_1/parser_g28_1_g30_1.c
- requires version 1.12 of µCNC
> fixed G28.1 G30.1 not updating imediatly issue

- i2c_eeprom/CHANGELOG.md
- spi_flash/CHANGELOG.md
- spi_flash/README.md
- spi_flash/spi_flash.c
- this module allows to store settings on a NOR Flash W25Qxxx
> W25Qxxx SPI Flash support to store settings

- sd_card_v2/CHANGELOG.md
- sd_card_v2/diskio.c
- sd_card_v2/diskio.h
- sd_card_v2/sd_card_v2.c
- stm32_sdio/CHANGELOG.md
- stm32_sdio/README.md
- stm32_sdio/bsp_driver_sd.c
- stm32_sdio/bsp_driver_sd.h
- stm32_sdio/sd_diskio.c
- stm32_sdio/sd_diskio.h
- stm32_sdio/stm32_sdio.c
- Modification of SD Card module to allow custom HW interfaces
- New STM32 SDIO support (MX Cube HAL)
> Integration of STM32 SDIO for SD module

- sd_card_v2/CHANGELOG.md
- sd_card_v2/diskio.c
- sd_card_v2/sd_card_v2.c
- enable macro to control SPI DMA usage
- added SD card automount on startup is available
> SD card module improvements

- joystick_v2/CHANGELOG.md
- joystick_v2/README.md
- joystick_v2/joystick_v2.c
New updated version of the analog joystick version based on [joystick module from Patryk Mierzyński](#65)
> Joystick v2
